# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               matthiasmunder.de
tagline:             'tagline will be here'
description:      'Short descriptions goes here'
url:                    http://matthiasmunder.de
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Matthias Munder
  url:                  http://matthiasmunder.de
  email:             matthiasmunder@gmail.com

# Custom vars
version:             1.0.0
