# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Matthias Christoph Munder
#tagline:           'A Jekyll theme'
description:  'Description goes here'
url:                 http://matthiasmunder.de
baseurl:             ''
paginate:            5

# About/contact
author:
  name:             Matthias Munder
  url:                  https://twitter.com/matthiasmunder
  email:             matthiasmunder@gmail.com

# Custom vars
version:             1.0.0
