# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:                  matthiasmunder.de | Content will follow soon
tagline:             'A blog about stuff'
description:      'Content will follow soon'
url:                    'http://matthiasmunder.de'
baseurl:             /
paginate:            7


# About/contact
author:
  name: "Matthias Munder"
  email: "matthiasmunder@gmail.com"
  url: "http://www.matthiasmunder.de"
  
# Custom vars
version:             2.0

# Social Media
github:				http://github.com/matthiasmunder
twitter:			    http://twitter.com/matthiasmunder
#disqus:            testnaringu

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu